### ISSUE TITLE
Document process and details for testing boosters

### ISSUE THREAD

**Issue by rhoads-zach** [fabric8-launcher/launcher-documentation#711]
* what goes on with `mvn clean verify -Popenshift,openshift-it`
* how do you update our tests
* what is used for testing

**Comment by Ladicek** [comment]
https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http has already been moved to Cube, so you can probably look at that. Specifically, you might want to look at the commit https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http/commit/6472fe60b70fd7937df2c7468a91e9d8fc6a032d?w=1 which shows what had to be added to the Maven project. (The dependency excludes for Surefire are Swarm-specific, because Swarm also uses Arquillian for unit testing outside of OpenShift.)

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-841
