### ISSUE TITLE
Instructions using git clone - openshift template doesn' t exist

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launcher/launcher-documentation#783]
The [instructions](https://appdev.openshift.io/docs/spring-boot-runtime.html#missions-intro) only refer to the workflow starting with a zip file but neither when the user follows the workflow where a project is created under a git repo, an openshift template deployed in an Openshift instance and build launched automatically

**Comment by rhoads-zach** [comment]
@cmoulliard are you asking us to add instructions for directly cloning the booster from the project repo (e.g. https://github.com/snowdrop/spring-boot-http-booster) without using the Fabric8 Launcher tool?

If so, that flow is out of scope for the docs.

**Comment by cmoulliard** [comment]
> directly cloning

No. What I'm saying here is that we only within the doc - guides describe the process = steps to play with an unzipped project which corresponds to the "download zip workflow" and never if the user select the "workflow" where a git project is created under his/her git account, build/deployment automated using the content of the .openshiftio/application.yaml template.

**Comment by rhoads-zach** [comment]
@cmoulliard this process is documented through using the launcher, hence:
https://appdev.prod-preview.openshift.io/docs/spring-boot-runtime.html#deploying-the-booster-using-launcher-oso_rest-api-oso

In the review section of the launcher, the user is given basic instructions for cloning their repo updating their booster. It also links off to the custom README file.

Additionally, the README file goes deeper into cloning, interacting, and pushing changes. It also links to the interaction section of the runtime guide.

We can continue the discussion of how this fits in to the docs, but moving this to low priority since it is documented.

**Comment by rhoads-zach** [comment]
moved to jira: https://issues.jboss.org/browse/RHOARDOC-23
