### ISSUE TITLE
Document Using Jolokia to monitor the JVM on OpenShift

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launcher/launcher-documentation#891]
Additional information: [Jolokia JVM monitoring in OpenShift](https://developers.redhat.com/blog/2016/03/30/jolokia-jvm-monitoring-in-openshift/)

Document a procedure for monitoring the CPU and Memory requirements of the JVM running your application on OpenShift using Jolokia.
This could be a worthy addition to the Runtime Dev guides  and could be included in the `Monitoring Your Application` section.

@cmoulliard FYI^^

Relevant content fromm the Spring Boot Upstream docs : https://docs.spring.io/spring-boot/docs/1.5.7.RELEASE/reference/html/production-ready-jmx.html

**Comment by cmoulliard** [comment]
FYI : Here is a project created showing how to expose the Jolokia Https Service as a route and query it using curl/htppie -> https://github.com/snowdrop/spring-boot-jolokia

Different modifications are required within a project in order to use jolokia :  
- Add a Service/Route for Jolokia HTTPS endpoint (default port is 8778)
- Add env var to the deploymentconfig in order to define the user/password to be used for access not issued through the OpenShift console / Kubernetes Api

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-1021
