### ISSUE TITLE
Integration test content

### ISSUE THREAD

**Issue by mocenas** [fabric8-launcher/launcher-documentation#924]
Just a topic for discussion. Should the docs contains some explanation of what is done in integration tests? And even what is tested?

**Comment by inoxx03** [comment]
@mocenas Thank you for bringing this up. Providing more background on the integration tests would be useful, I believe (IIRC we've already had an issue for it in this repo, but the change got deferred in favor of other priority items).
I think we should focus on describing what happens during the testing process, and what the expected output of the integration testing is. 
Questions like:
- Why do we want integration tests
- What happens in the process of testing (the test instance of the application is deployed, what the individual tests do, ... )
- What kind of output should the user expect in cases of test success and test failure.
- what happens when the tests fail (maybe some troubleshooting instructions, too)
should be addressed.

**Comment by rhoads-zach** [comment]
moved here: https://issues.jboss.org/browse/RHOARDOC-1054
