### ISSUE TITLE
Spring Boot release notes doesn't contain supported artifacts

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launcher/launcher-documentation#952]
Some components we deliver with Spring Boot are supported AFAIK; that mainly includes Tomcat. The RN only contains one giant table of "tested and supported" components, which contains the community Tomcat version. That implies that it's not supported. Funnily enough, the version of `org.eclipse:jdt` in that table is `4.4.2.redhat-1`, which is a productized version -- unlike all other components in the same table, which are included in their community version (even though we actually ship a productized one).

Or, to make it shorter: the listing of Spring Boot artifacts in the release notes is a mess.

**Comment by inoxx03** [comment]
@Ladicek Thank you.
It is not just the listing, IMHO it is the entire support situation :)
The Spring Boot team requested that we use  _Tested and Verifed_ instead of _Supported_ when referring to Spring Boot artifacts shipped with RHOAR.
John and Jay have also requested that we specify in the RN that Spring Boot is maintained by pivotal, so we can not provide support for it.
I have sourced the version information and artifact names for SpringBoot version from the `1.5.8.Final` BOM.
When I asked the Spring Boot team to check the artifact list and versions, nobody objected to the current state.
I'll make sure to re-check again and update the list. We will not be shipping the RN  with incorrect information:)

**Comment by Ladicek** [comment]
Yea agreed about the support situation :-) FTR, we use "tested and verified" for Spring Boot and "tested" for other runtimes, which is weird :-), and also we use the word "certified" for this kind of stuff in the WildFly Swarm guide...

**Comment by inoxx03** [comment]
Currently Investigating this...

**Comment by inoxx03** [comment]
The content detailing the supported configurations and integrations for each of the productized runtimes has been incorporated into the Release notes and [published](https://access.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/red_hat_openshift_application_runtimes_release_notes/#rn-supported-configurations-and-integrations) under RHOAR docs on the Cutsomer Portal.

This content delineates the current support situation around specific components, configurations and integrations with other technologies.
Tested and unsupported components are also called out explicitly.

For Spring Boot the content also provides the explanation of the 4 different supportability tiers.

The content is as detailed as possible given the current state of decision-making regarding the support offered for RHOAR. Further modifications to it might be necessary to accomodate later changes. 

There might still be some duplication of RN content, but no available information should be missing now.
I propose we close this issue.
